routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'auth'],function (){
    Route::resource('company','CompanyController');
    Route::resource('category','CategoryController');
    Route::resource('pill','PillController');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="row">
                        <div class="col-sm">
                            <a href="{{ route('company.create') }}" class="btn btn-secondary btn-block">Add new Company</a>
                        </div>
                        <div class="col-sm">
                            <a href="{{ route('category.create') }}" class="btn btn-secondary btn-block">Add new Category</a>
                        </div>
                        <div class="col-sm">
                            <a href="{{ route('pill.create') }}" class="btn btn-secondary btn-block">Add new Pill</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection