routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'auth'],function (){
    Route::resource('company','CompanyController');
    Route::resource('category','CategoryController');
    Route::resource('pill','PillController');
});

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    protected $fillable = [
        'name'
    ];

    /*
     |------------------------------------------------------
     | Getters
     |------------------------------------------------------
     */
    public function getPathAttribute()
    {
        return asset('uploads/pills/'.$this->name);
    }
}

app/Pill.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pill extends Model
{
    protected $fillable = [
        'name',
        'company_id',
        'description',
        'image_id'
    ];

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function image()
    {
        return $this->belongsTo(Image::class);
    }
}

app/Http/Controllers/PillController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Company;
use App\Image;
use App\Pill;
use Illuminate\Http\Request;

class PillController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pills = Pill::all();
        return view('pill.index',compact('pills'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $companies = Company::all();

        return view('pill.create',compact('categories','companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'category' => 'required',
            'company' => 'required',
        ]);

        $pill = Pill::create([
            'name' => $request->name,
            'description' => $request->description,
            'company_id' => $request->company,
        ]);

        $pill->categories()->sync($request->category);

        if ($request->has('image')) {
            $filename = microtime(true).'.'.$request->file('image')->extension();
            $path = 'uploads/pills';

            $request->file('image')->move($path, $filename);

            $image = Image::create([
                'name' => $filename
            ]);

            $pill->update(['image_id' => $image->id]);
        }

        return redirect()->route('pill.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pill/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">New Pill</div>

                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form id="pill_form" action="{{ route('pill.store') }}" method="post" onsubmit="checkForm(event)" enctype='multipart/form-data'>
                            @csrf()
                            <div class="form-group">
                                <label for="name">Pill name</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" placeholder="Type name here...">
                            </div>
                            <div class="form-group">
                                <label for="category">Category</label>
                                <select name="category[]" id="category" class="form-control select2" multiple="multiple">
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="category">Company</label>
                                <select name="company" id="company" class="form-control">
                                    <option value="">Select Company</option>
                                    @foreach($companies as $company)
                                        <option value="{{ $company->id }}">{{ $company->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="name">Pill image</label>
                                <input type="file" id="image" name="image">
                            </div>
                            <div class="form-group">
                                <label for="description">Pill description</label>
                                <textarea name="description" id="description" cols="30" rows="10" class="form-control"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('footer-scripts')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
@endsection

resources/views/pill/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Pills</div>

                    <div class="card-body">
                        <ul class="list-group">
                            @foreach($pills as $pill)
                                <li class="list-group-item">
                                    {{ $pill->name }}
                                    @if($pill->image)
                                        <p>
                                            <img src="{{ $pill->image->path }}" alt="{{ $pill->name }}" class="img-thumbnail">
                                        </p>
                                    @endif
                                    <p>
                                        <strong>Company: </strong>
                                        {{ $pill->company->name }}
                                    </p>
                                    <p>
                                        <strong>Categories: </strong>
                                        {{ implode(', ',$pill->categories->pluck('name')->toArray()) }}
                                    </p>
                                    <p>
                                        <strong>Description: </strong>
                                        {{ $pill->description }}
                                    </p>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection